name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Code checkout
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Maven Checkstyle
        run: mvn checkstyle:checkstyle
